config/routes.rb
require 'sidekiq/web'
NewsAggregator::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'entries#index'
  get 'away' => 'away#go'
  get '/znaigorod', :to => 'entries#znaigorod'
  get ':period', :to => 'entries#index', :as => :period, :constraints => {:period => Regexp.new(Entry.available_periods.join("|"))}
  get ':sort_by', :to => 'entries#index', :as => :sort_by, :constraints => {:sort_by => Regexp.new(Entry.available_sorts.join("|"))}

  get ':kind', :to => 'suggested_entries#index', :as => :suggested_list, :constraints => {:kind => Regexp.new(SuggestedEntry.available_types.join("|"))}
  resources :suggested_entries, :only => [:new, :create]

  namespace :manage do
    resources :sources
    resources :suggested_entries, :except => [:new, :create,:show] do
      get :approve
      get ':entry_type', :to => 'suggested_entries#entry_type', :on => :collection, :as => :entry_type, :constraints => {:entry_type => Regexp.new(SuggestedEntry.available_types.join("|"))}
    end
    root to: "sources#index"
  end

  %w[about].each do |method|
    get method => "cooperations##{method}"
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :source
  has_many :statistics, :order => 'id desc'
  attr_accessible :title, :url, :description, :published_at
  validates_presence_of :title, :url, :published_at
  validates_uniqueness_of :url
  before_save :default_values

  scope :newest, -> { where('published_at >= :time', {:time => Time.zone.now-12.hour}) }
  scope :today, -> { where('published_at >= :time', {:time => Time.zone.now.beginning_of_day}) }
  scope :threedays, -> { where('published_at >= :time', {:time => Time.zone.now.beginning_of_day - 3.days}) }
  scope :weekly, -> { where('published_at >= :time', {:time => Time.zone.now - 7.days}) }
  scope :monthly, -> { where('published_at >= :time', {:time => Time.zone.now - 30.days}) }
  scope :alltime

  scope :rating, -> { order('rating desc') }
  scope :novelty, -> { order('published_at desc') }

  searchable do
    text :title, :stored => true
    text :description
    string(:source) { source.source }
    float :rating
    time :published_at
  end

  def self.available_periods
    ['newest', 'today', 'threedays', 'weekly', 'monthly', 'alltime']
  end

  def self.available_sorts
    ['rating', 'novelty']
  end

  def stripped_url
    url.sub!(/https\:\/\/www./, '') if url.include? "https://www."
    url.sub!(/http\:\/\/www./, '')  if url.include? "http://www."
    url.sub!(/www./, '')            if url.include? "www."
    url.sub!(/http\:\/\//,'')       if url.include? "http://"
    return url
  end

  def summary_comments_count
    vk_comments_count.to_i + facebook_comments_count.to_i
  end

  def summary_likes_count
    vk_likes_count.to_i + facebook_likes_count.to_i
  end

  def link
    AwayLink.to(url)
  end

  private

  def default_values
    self.url = self.url.strip
    self.vk_shares_count ||= 0
    self.vk_likes_count ||= 0
    self.vk_comments_count ||= 0
    self.facebook_shares_count ||= 0
    self.facebook_comments_count ||= 0
    self.facebook_likes_count ||= 0
    self.twitter_shares_count ||= 0
    update_rating
  end

  def update_rating
    self.rating =
      self.twitter_shares_count +
      self.vk_shares_count +
      self.vk_likes_count*0.5 +
      self.vk_comments_count*0.5 +
      self.facebook_shares_count +
      self.facebook_comments_count*0.5 +
      self.facebook_likes_count*0.5
  end
end

# == Schema Information
#
# Table name: entries
#
#  id                      :integer          not null, primary key
#  title                   :text
#  url                     :string(255)
#  description             :text
#  published_at            :datetime
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  rating                  :float            default(0.0)
#  source_id               :integer
#  vk_shares_count         :integer
#  vk_likes_count          :integer
#  vk_comments_count       :integer
#  vk_updated_at           :datetime
#  facebook_shares_count   :integer
#  facebook_comments_count :integer
#  facebook_updated_at     :datetime
#  twitter_shares_count    :integer
#  twitter_updated_at      :datetime
#

app/controllers/entries_controller.rb
# encoding: utf-8
class EntriesController < ApplicationController
  helper_method :page, :current_period, :current_source, :search_query, :current_sort

  def index
    collection = if params['utf8']
      HasSearcher.searcher(:entries, :q => search_query, :source => current_source)
        .send(current_period).send(current_sort)
        .paginate(:page => page, :per_page => per_page).hits
    else
      Entry.send(current_period).send(current_sort).page(page).per(per_page)
    end
    @entries_wrapper = EntriesWrapper.new(collection)
    render :partial => 'entries_body' and return if request.xhr?
  end

  def znaigorod
     @entries_wrapper = EntriesWrapper.new(Entry.send('newest').send('rating').page(1).per(6))
     render layout: false
  end

  protected

  def page
    page = params[:page].to_i
    page.zero? ? 1 : page
  end

  def per_page
    15
  end

  def current_period
    (Entry.available_periods && params[:period]) || Entry.available_periods.first
  end

  def current_sort
    (Entry.available_sorts && params[:sort_by]) || Entry.available_sorts.first
  end

  def search_query
    params.try(:[], 'search').try(:[], 'q')
  end

  def current_source
    params.try(:[], 'search').try(:[], 'source')
  end
end

app/views/entries/_entries_body.html.erb
<% @entries_wrapper.collection.each do |entry| %>
  <%= render entry %>
<% end %>

<tr>
  <td>
    <%= link_to_next_page @entries_wrapper.paginateable_collection, 'Загрузить еще 15 новостей', :remote => true, :class => 'js-next btn next_page', :params => params %>
  </td>
  <td colspan='6'>
    <div class='source'>
      <%= simple_form_for :search, :url => period_path(current_period, params), :method => :get do |form| %>
        <div class='submit'>
          <%= form.submit 'Фильтр', :class => :btn %>
        </div>
        <%= form.input :source,
          :as => :select,
          :label => false,
          :collection => Source.all.group_by(&:source).keys.sort,
          :selected => current_source,
          :include_blank => true,
          :required => false
        %>
      <%= form.input :q, :as => :hidden, :input_html => {:value => search_query} %>
      <% end %>
    </div>
  </td>
</tr>

app/views/entries/_entry.html.erb
<tr>
  <td class='left'>
    <span class='favicon'><%= image_tag entry.source.favicon, :size => '16x16' %></span>
    <p><%= link_to entry.title.gilensize.html_safe, entry.link, :target => '_blank' %></p>
  </td>
  <td class='rating'><%= entry.vk_shares_count.to_i %></td>
  <td class='rating'><%= entry.facebook_shares_count.to_i %></td>
  <td class='rating'><%= entry.twitter_shares_count.to_i %></td>
  <td class='rating'><%= entry.summary_likes_count %></td>
  <td class='rating'><%= entry.summary_comments_count %></td>
  <td class='rating'><%= entry.rating %></td>
</tr>

app/views/entries/_hit_wrapper.html.erb
<tr>
  <td class='left'>
    <span class='favicon'><%= image_tag hit_wrapper.result.source.favicon, :size => '16x16' %></span>
    <p><%= link_to hit_wrapper.title.html_safe, hit_wrapper.result.url, :target => '_blank' %></p>
  </td>
  <td class="rating"><%= hit_wrapper.result.vk_shares_count.to_i %></td>
  <td class="rating"><%= hit_wrapper.result.facebook_shares_count.to_i %></td>
  <td class="rating"><%= hit_wrapper.result.twitter_shares_count.to_i %></td>
  <td class="rating"><%= hit_wrapper.result.vk_likes_count.to_i %></td>
  <td class="rating"><%= hit_wrapper.result.summary_comments_count %></td>
  <td class="rating"><%= hit_wrapper.result.rating %></td>
</tr>

app/views/entries/index.html.erb
<table>
  <thead>
    <tr>
      <th class='left'>Последние новости</th>
      <th><span class='vkontakt' title='Упоминания ВКонтакте'></span></th>
      <th><span class='facebook' title='Упоминания в Facebook'></span></th>
      <th><span class='twitter' title='Упоминания в Twitter'></span></th>
      <th><span class='likes' title='Понравилось во Вконтакте и в Facebook-е'></span></th>
      <th><span class='comments' title='Комментарии во Вконтакте и в Facebook-е'></span></th>
      <th><span class='rating' title='Общий рейтинг'></span></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'entries_body' %>
  </tbody>
</table>

app/views/entries/znaigorod.html.erb
<div class='news_list_wrapper'>
  <h1><%= link_to '%title%', 'http://news.znaigorod.ru' %></h1>
  <table>
    <thead>
      <tr>
        <th class='left'>
          <div class='timestamp'>
            <span>За</span>
            <ul>
              <% Entry.available_periods.each do |scope| %>
                <li<%= " class='selected'".html_safe if current_period == scope %>>
                  <%= link_to t("period.#{scope}"), period_url(scope) %>
                </li>
              <% end %>
            </ul>
          </div>
        </th>
        <th><span class='vkontakt' title='Упоминания ВКонтакте'></span></th>
        <th><span class='facebook' title='Упоминания в Facebook'></span></th>
        <th><span class='twitter' title='Упоминания в Twitter'></span></th>
        <th><span class='likes' title='Понравилось во Вконтакте и в Facebook-е'></span></th>
        <th><span class='comments' title='Комментарии во Вконтакте и в Facebook-е'></span></th>
        <th><span class='rating' title='Общий рейтинг'></span></th>
      </tr>
    </thead>
    <tbody>
      <% @entries_wrapper.collection.each do |entry| %>
        <%= render entry %>
      <% end %>
    </tbody>
  </table>
</div>