config/routes.rb
require 'sidekiq/web'
NewsAggregator::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'entries#index'
  get 'away' => 'away#go'
  get '/znaigorod', :to => 'entries#znaigorod'
  get ':period', :to => 'entries#index', :as => :period, :constraints => {:period => Regexp.new(Entry.available_periods.join("|"))}
  get ':sort_by', :to => 'entries#index', :as => :sort_by, :constraints => {:sort_by => Regexp.new(Entry.available_sorts.join("|"))}

  get ':kind', :to => 'suggested_entries#index', :as => :suggested_list, :constraints => {:kind => Regexp.new(SuggestedEntry.available_types.join("|"))}
  resources :suggested_entries, :only => [:new, :create]

  namespace :manage do
    resources :sources
    resources :suggested_entries, :except => [:new, :create,:show] do
      get :approve
      get ':entry_type', :to => 'suggested_entries#entry_type', :on => :collection, :as => :entry_type, :constraints => {:entry_type => Regexp.new(SuggestedEntry.available_types.join("|"))}
    end
    root to: "sources#index"
  end

  %w[about].each do |method|
    get method => "cooperations##{method}"
  end
end

app/views/shared/_filter.html.erb
<div class='filter'>
  <div class='timestamp'>
    <span>За</span>
    <ul>
      <% Entry.available_periods.each do |scope| %>
        <li<%= " class='selected'".html_safe if current_period == scope %>>
          <%= link_to t("period.#{scope}"), period_path(scope, params) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class='sort_by'>
    <span>По</span>
    <ul>
      <% Entry.available_sorts.each do |sort| %>
        <li<%= " class='selected'".html_safe if current_sort == sort %>>
          <%= link_to t("sort_by.#{sort}"), sort_by_path(sort, params) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class='search'>
  <%= simple_form_for :search, :url => period_path(current_period, params), :method => :get do |f| %>
    <div class='submit'>
      <%= f.submit 'Найти' %>
    </div>
    <%= f.input :q, :as => :string, :label => false, :placeholder => 'Поиск', :input_html => { :value => search_query } %>
    <%= f.input :source, :as => :hidden, :input_html => {:value => current_source} %>
  <% end %>
</div>